<div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f8f9fa; margin: 0; padding: 20px 0; color: #333; line-height: 1.6;">
    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width: 680px; margin: 0 auto; background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.1); border: 1px solid #e2e8f0;">
        <tr>
            <td style="background: linear-gradient(135deg, #8b5cf6 0%, #a855f7 100%); padding: 40px 30px; text-align: center; color: white;">
                @php
                    $logoSetting = \App\Helpers\CommonHelper::masterSettingsName('logo');
                    $nameSetting = \App\Helpers\CommonHelper::masterSettingsName('name');
                    $logo = $logoSetting['master_value'] ?? '';
                    $companyName = $nameSetting['master_value'] ?? config('app.name');
                @endphp
                @if(!empty($logo))
                <div style="margin-bottom: 20px;">
                    <img src="{{ $logo }}" alt="{{ $companyName }}" style="max-width: 140px; border-radius: 12px; border: 4px solid rgba(255,255,255,0.9); box-shadow: 0 8px 20px rgba(0,0,0,0.15);">
                </div>
                @endif
                @if(!empty($dmc_logo))
                <div style="margin-bottom: 16px;">
                    <img src="{{ $dmc_logo }}" alt="{{ $dmc_name ?? 'DMC' }}" style="max-width: 100px; height: auto; border-radius: 8px; border: 3px solid rgba(255,255,255,0.9); background: white; padding: 6px;">
                </div>
                @endif
                <h1 style="margin: 0; font-size: 26px; font-weight: 700; letter-spacing: 0.5px; color: white;">
                    New AI Generated Tour
                </h1>
                <p style="margin: 10px 0 0 0; font-size: 16px; opacity: 0.95;">A new tour has been intelligently generated by the AI Tour Creation Engine on Travclicks.</p>
                <div style="display: inline-block; background: rgba(255,255,255,0.2); border-radius: 50px; padding: 8px 20px; margin-top: 18px; font-weight: 700; font-size: 13px; letter-spacing: 1px; border: 2px solid rgba(255,255,255,0.3);">
                    AI GENERATED
                </div>
            </td>
        </tr>

        <tr>
            <td style="padding: 40px 35px;">
                <p style="font-size: 20px; font-weight: 600; margin: 0 0 8px 0; color: #1e293b; text-align: center;">
                    Hello {{ $dmc_name ?? 'DMC Partner' }},
                </p>
                <p style="font-size: 16px; text-align: center; color: #64748b; margin: 0 0 30px 0; line-height: 1.7;">
                    A new tour has been automatically generated by the Travclicks AI Engine based on the available package, destination, and travel requirements. Please review the generated itinerary and associated services from your dashboard.
                </p>

                <div style="background: linear-gradient(135deg, #f5f3ff 0%, #ede9fe 100%); border-radius: 16px; padding: 28px 26px; margin-bottom: 30px; border: 2px solid #c4b5fd;">
                    <h3 style="font-size: 18px; font-weight: 700; margin: 0 0 20px 0; color: #7c3aed; padding-bottom: 12px; border-bottom: 2px solid #c4b5fd;">
                    AI Generated Tour Details
                    </h3>

                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                        <tr>
                            <td style="padding: 8px 0; font-size: 13px; color: #64748b; font-weight: 600; text-transform: uppercase; width: 42%;">Tour ID</td>
                            <td style="padding: 8px 0; font-size: 15px; color: #1e293b; font-weight: 600;">{{ $tour_display_id ?? 'N/A' }}</td>
                        </tr>
                        @if(!empty($package_id))
                        <tr>
                            <td style="padding: 8px 0; font-size: 13px; color: #64748b; font-weight: 600; text-transform: uppercase;">Package ID</td>
                            <td style="padding: 8px 0; font-size: 15px; color: #1e293b; font-weight: 600;">{{ $package_id }}</td>
                        </tr>
                        @endif
                        <tr>
                            <td style="padding: 8px 0; font-size: 13px; color: #64748b; font-weight: 600; text-transform: uppercase;">Country</td>
                            <td style="padding: 8px 0; font-size: 15px; color: #1e293b; font-weight: 600;">{{ $country ?? ($destination ?? 'N/A') }}</td>
                        </tr>
                        @if(!empty($cities_label))
                        <tr>
                            <td style="padding: 8px 0; font-size: 13px; color: #64748b; font-weight: 600; text-transform: uppercase;">Cities</td>
                            <td style="padding: 8px 0; font-size: 15px; color: #1e293b; font-weight: 600;">{{ $cities_label }}</td>
                        </tr>
                        @endif
                        <tr>
                            <td style="padding: 8px 0; font-size: 13px; color: #64748b; font-weight: 600; text-transform: uppercase;">Travel Dates</td>
                            <td style="padding: 8px 0; font-size: 15px; color: #1e293b; font-weight: 600;">{{ $check_in_date ?? 'N/A' }} – {{ $check_out_date ?? 'N/A' }}</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px 0; font-size: 13px; color: #64748b; font-weight: 600; text-transform: uppercase; vertical-align: top;">Guests</td>
                            <td style="padding: 8px 0; font-size: 15px; color: #1e293b; font-weight: 600;">
                                <div style="margin-bottom: 6px;">{{ $total_guests ?? 0 }} total guests</div>
                                <div>
                                    @if(($adults ?? 0) > 0)
                                    <span style="display: inline-block; background: #fff; padding: 4px 10px; border-radius: 6px; border: 1px solid #c4b5fd; margin: 0 6px 6px 0; font-size: 14px;">
                                        Adults: <strong style="color: #7c3aed;">{{ $adults }}</strong>
                                    </span>
                                    @endif
                                    @if(($children ?? 0) > 0)
                                    <span style="display: inline-block; background: #fff; padding: 4px 10px; border-radius: 6px; border: 1px solid #c4b5fd; margin: 0 6px 6px 0; font-size: 14px;">
                                        Children: <strong style="color: #7c3aed;">{{ $children }}</strong>
                                    </span>
                                    @endif
                                    @if(($infants ?? 0) > 0)
                                    <span style="display: inline-block; background: #fff; padding: 4px 10px; border-radius: 6px; border: 1px solid #c4b5fd; margin: 0 6px 6px 0; font-size: 14px;">
                                        Infants: <strong style="color: #7c3aed;">{{ $infants }}</strong>
                                    </span>
                                    @endif
                                    @if(($adults ?? 0) === 0 && ($children ?? 0) === 0 && ($infants ?? 0) === 0)
                                    <span style="font-size: 14px; color: #64748b;">No guest breakdown provided</span>
                                    @endif
                                </div>
                            </td>
                        </tr>
                        @if(!empty($agent_name) || !empty($agency_name))
                        <tr>
                            <td style="padding: 8px 0; font-size: 13px; color: #64748b; font-weight: 600; text-transform: uppercase;">Agent</td>
                            <td style="padding: 8px 0; font-size: 15px; color: #1e293b; font-weight: 600;">
                                {{ $agent_name ?? 'N/A' }}
                                @if(!empty($agency_name))
                                — {{ $agency_name }}
                                @endif
                            </td>
                        </tr>
                        @endif
                        <tr>
                            <td style="padding: 8px 0; font-size: 13px; color: #64748b; font-weight: 600; text-transform: uppercase;">Booked On</td>
                            <td style="padding: 8px 0; font-size: 15px; color: #1e293b; font-weight: 600;">{{ $booked_at ?? now()->format('M d, Y H:i') }}</td>
                        </tr>
                    </table>
                </div>

                @if(!empty($booked_services) && count($booked_services) > 0)
                <div style="background: linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%); border-radius: 16px; padding: 28px 26px; margin-bottom: 30px; border: 2px solid #6ee7b7;">
                    <h3 style="font-size: 18px; font-weight: 700; margin: 0 0 20px 0; color: #047857; padding-bottom: 12px; border-bottom: 2px solid #6ee7b7;">
                        Booked Services
                    </h3>
                    <table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-collapse: collapse;">
                        <tr>
                            <td style="padding: 10px 8px; font-size: 12px; color: #047857; font-weight: 700; text-transform: uppercase; border-bottom: 2px solid #6ee7b7;">Type</td>
                            <td style="padding: 10px 8px; font-size: 12px; color: #047857; font-weight: 700; text-transform: uppercase; border-bottom: 2px solid #6ee7b7;">Service</td>
                            <td style="padding: 10px 8px; font-size: 12px; color: #047857; font-weight: 700; text-transform: uppercase; border-bottom: 2px solid #6ee7b7;">When</td>
                        </tr>
                        @foreach($booked_services as $service)
                        <tr>
                            <td style="padding: 10px 8px; font-size: 14px; color: #1e293b; font-weight: 600; vertical-align: top; width: 22%;">{{ $service['type'] ?? 'Service' }}</td>
                            <td style="padding: 10px 8px; font-size: 14px; color: #1e293b; vertical-align: top;">{{ $service['name'] ?? '—' }}</td>
                            <td style="padding: 10px 8px; font-size: 13px; color: #64748b; vertical-align: top; white-space: nowrap;">
                                @if(!empty($service['day']))
                                {{ $service['day'] }}
                                @endif
                                @if(!empty($service['day']) && !empty($service['date']))
                                <br>
                                @endif
                                @if(!empty($service['date']))
                                {{ $service['date'] }}
                                @endif
                                @if(empty($service['day']) && empty($service['date']))
                                —
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </table>
                </div>
                @endif

                <div style="background: linear-gradient(135deg, #fefce8 0%, #fef3c7 100%); border-radius: 16px; padding: 28px 22px; text-align: center; margin: 30px 0; border: 2px solid #fbbf24;">
                    <h3 style="font-size: 18px; font-weight: 700; margin: 0 0 12px 0; color: #92400e;">Manage This Tour</h3>
                    <p style="font-size: 15px; color: #92400e; margin: 0 0 18px 0;">Open your dashboard to confirm services, assign guides, and update the itinerary.</p>
                    <a href="{{ $dashboard_link ?? url('/') }}" style="display: inline-block; background: linear-gradient(135deg, #8b5cf6 0%, #a855f7 100%); color: #ffffff !important; text-decoration: none; padding: 16px 32px; border-radius: 12px; font-weight: 700; font-size: 16px; letter-spacing: 0.5px; box-shadow: 0 6px 20px rgba(139, 92, 246, 0.35);">
                        Open DMC Dashboard
                    </a>
                </div>

                <p style="text-align: center; font-size: 15px; color: #64748b; margin: 0;">
                    Questions? Contact <a href="mailto:support@travclicks.com" style="color: #7c3aed; font-weight: 600; text-decoration: none;">support@travclicks.com</a>
                </p>
            </td>
        </tr>

        <tr>
            <td style="background: linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 100%); padding: 28px; text-align: center; font-size: 13px; color: #64748b; border-top: 1px solid #e2e8f0;">
                <p style="margin: 0 0 8px 0; font-style: italic; color: #7c3aed; font-weight: 600;">
                    Empowering Destination Management through Smart Automation
                </p>
                <p style="margin: 0;">&copy; {{ date('Y') }} {{ $companyName ?? config('app.name') }}. All rights reserved.</p>
            </td>
        </tr>
    </table>
</div>
