export const SUPPORTED_COUNTRIES = [
  "Singapore",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Australia",
  "New Zealand",
  "Laos",
  "Cambodia",
  "UAE",
];

export const LANDING_HERO_SLIDES = [
  {
    id: 1,
    image: "/img/masthead/1/bg.webp",
    title: "Reimagine Travel Operations With AI Auto Responder",
    subtitle:
      "An always-on AI engine that automates operations, accelerates sales, and delivers real-time traveler experiences for travel agencies.",
    location: "Powered by Travclicks AI",
  },
  {
    id: 2,
    image: "/img/masthead/3/bg.png",
    title: "Smart Automation. Seamless Engagement.",
    subtitle:
      "Replace slow manual processes with AI-driven workflows, automated bookings, and intelligent quotations — all in one unified system.",
    location: "Smart Travel Operations",
  },
  {
    id: 3,
    image: "/img/masthead/7/bg.png",
    title: "Built for Growing Travel Enterprises",
    subtitle:
      "Serving partners across Singapore, Malaysia, Thailand, Indonesia, Australia, New Zealand, Laos, Cambodia, and UAE.",
    location: "Asia Pacific & Middle East",
  },
];

export const LANDING_DESTINATIONS = [
  {
    id: 1,
    name: "Marina Bay",
    image: "/Images/landingpage/destination/Bali/1.jpg",
    description: "City sightseeing, venues, and business travel support",
    country: "Singapore",
  },
  {
    id: 2,
    name: "Sentosa",
    image: "/Images/landingpage/destination/Bali/2.jpg",
    description: "Resort stays and leisure attractions",
    country: "Singapore",
  },
  {
    id: 3,
    name: "Kuala Lumpur",
    image: "/Images/landingpage/destination/Malaysia/2.jpg",
    description: "Urban stays, city tours, and regional extensions",
    country: "Malaysia",
  },
  {
    id: 4,
    name: "Penang",
    image: "/Images/landingpage/destination/Malaysia/3.jpg",
    description: "Heritage circuits and coastal leisure programmes",
    country: "Malaysia",
  },
  {
    id: 5,
    name: "Bangkok",
    image: "/Images/landingpage/destination/Thailand/3.jpg",
    description: "City experiences, temples, and river programmes",
    country: "Thailand",
  },
  {
    id: 6,
    name: "Phuket",
    image: "/Images/landingpage/destination/Malaysia/5.jpg",
    description: "Island resorts, beaches, and day excursions",
    country: "Thailand",
  },
  {
    id: 7,
    name: "Bali",
    image: "/Images/landingpage/destination/Bali/3.jpg",
    description: "Cultural circuits, resorts, and leisure programmes",
    country: "Indonesia",
  },
  {
    id: 8,
    name: "Jakarta",
    image: "/Images/landingpage/destination/Bali/5.jpg",
    description: "Urban stays, meetings, and city-based itineraries",
    country: "Indonesia",
  },
  {
    id: 9,
    name: "Sydney",
    image: "/Images/landingpage/destination/Indonesia/5.jpg",
    description: "Harbour city stays, day tours, and regional extensions",
    country: "Australia",
  },
  {
    id: 10,
    name: "Melbourne",
    image: "/Images/landingpage/destination/Vietnam/6.jpg",
    description: "City culture, coastal drives, and group travel support",
    country: "Australia",
  },
  {
    id: 11,
    name: "Auckland",
    image: "/Images/landingpage/destination/Vietnam/4.jpg",
    description: "Gateway city stays and North Island excursions",
    country: "New Zealand",
  },
  {
    id: 12,
    name: "Queenstown",
    image: "/Images/landingpage/destination/Vietnam/5.jpg",
    description: "Adventure and scenic leisure programmes",
    country: "New Zealand",
  },
  {
    id: 13,
    name: "Luang Prabang",
    image: "/Images/landingpage/destination/Bali/1.jpg",
    description: "Heritage towns, temples, and cultural journeys",
    country: "Laos",
  },
  {
    id: 14,
    name: "Vientiane",
    image: "/Images/landingpage/destination/Bali/2.jpg",
    description: "Capital stays and Mekong-side experiences",
    country: "Laos",
  },
  {
    id: 15,
    name: "Siem Reap",
    image: "/Images/landingpage/destination/Vietnam/1.jpg",
    description: "Angkor circuits and cultural leisure stays",
    country: "Cambodia",
  },
  {
    id: 16,
    name: "Phnom Penh",
    image: "/Images/landingpage/destination/Vietnam/2.jpg",
    description: "Capital city stays and riverside programmes",
    country: "Cambodia",
  },
  {
    id: 17,
    name: "Dubai",
    image: "/Images/landingpage/destination/Vietnam/3.jpg",
    description: "City highlights, desert experiences, and luxury stays",
    country: "UAE",
  },
  {
    id: 18,
    name: "Abu Dhabi",
    image: "/Images/landingpage/destination/Vietnam/6.jpg",
    description: "Cultural landmarks and premium leisure programmes",
    country: "UAE",
  },
];

export const LANDING_TOURS = [
  {
    id: 1,
    title: "Singapore City & Marina Bay Programme",
    location: "Singapore",
    duration: "4 Days / 3 Nights",
    image: "/Images/landingpage/destination/Bali/1.jpg",
    country: "Singapore",
  },
  {
    id: 2,
    title: "Kuala Lumpur & Genting Highlights",
    location: "Malaysia",
    duration: "5 Days / 4 Nights",
    image: "/Images/landingpage/destination/Malaysia/2.jpg",
    country: "Malaysia",
  },
  {
    id: 3,
    title: "Bangkok & Phuket Combined Circuit",
    location: "Thailand",
    duration: "6 Days / 5 Nights",
    image: "/Images/landingpage/destination/Thailand/3.jpg",
    country: "Thailand",
  },
  {
    id: 4,
    title: "Bali Cultural & Leisure Circuit",
    location: "Indonesia",
    duration: "6 Days / 5 Nights",
    image: "/Images/landingpage/destination/Bali/3.jpg",
    country: "Indonesia",
  },
  {
    id: 5,
    title: "Sydney Harbour & Blue Mountains",
    location: "Australia",
    duration: "5 Days / 4 Nights",
    image: "/Images/landingpage/destination/Indonesia/5.jpg",
    country: "Australia",
  },
  {
    id: 6,
    title: "Auckland & Rotorua Experience",
    location: "New Zealand",
    duration: "6 Days / 5 Nights",
    image: "/Images/landingpage/destination/Vietnam/4.jpg",
    country: "New Zealand",
  },
  {
    id: 7,
    title: "Luang Prabang Heritage Journey",
    location: "Laos",
    duration: "4 Days / 3 Nights",
    image: "/Images/landingpage/destination/Bali/1.jpg",
    country: "Laos",
  },
  {
    id: 8,
    title: "Siem Reap Angkor Discovery",
    location: "Cambodia",
    duration: "4 Days / 3 Nights",
    image: "/Images/landingpage/destination/Vietnam/1.jpg",
    country: "Cambodia",
  },
  {
    id: 9,
    title: "Dubai City & Desert Experience",
    location: "UAE",
    duration: "5 Days / 4 Nights",
    image: "/Images/landingpage/destination/Vietnam/3.jpg",
    country: "UAE",
  },
];
